version: '3'
services:
  postgres:
    image: 'postgres:latest'

    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
      image: dpage/pgadmin4

      env_file:
        - .env

      ports:
        - "54321:80"

      depends_on:
        - postgres
  

  
